# Site settings
title: Roadmap to CERN
SEOTitle: Roadmap to CERN
header-img: img/cosmic.jpg
email: saskia.poldmaa@gmail.com
description: "A roadmap to CERN, brought to you by team Mavericks - winners of BL4S 2024 competition. | Blog + Learning materials"
keyword: "BL4S, Detectors, Data Acquisition, CERN, Geneva, Muons, T10 Beamline"
url: "guilyx.github.com" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

collections:
  articles:
    output: true
    

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: saskiapoldmaa
twitter_username: rangonomics
#facebook_username:  huxpro
linkedin_username:  saskia-põldmaa-2a3b72266

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-L60Z89VR35" # Format: UA-xxxxxx-xx
ga_domain: guilyx.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Saskia Põldmaa <br> Member of Mavericks"
sidebar-avatar: https://raw.githubusercontent.com/saskiapoldmaa/saskiapoldmaa.github.io/master/img/portree.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true

# Friends
friends:
  [
    { title: "Open PR to be featured!", href: "https://github.com/guilyx/guilyx.github.io/pulls" },
  ]
